# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AirPatrol.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1911, 1031))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 430, 501, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(190, 0, 211, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(10, 400, 501, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(180, 380, 211, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 501, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 0, 471, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_13)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 30, 451, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 449, 293))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.remove_waypoint_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.remove_waypoint_btn.setGeometry(QtCore.QRect(390, 260, 51, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_waypoint_btn.sizePolicy().hasHeightForWidth())
        self.remove_waypoint_btn.setSizePolicy(sizePolicy)
        self.remove_waypoint_btn.setObjectName("remove_waypoint_btn")
        self.upload_mission_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.upload_mission_btn.setGeometry(QtCore.QRect(310, 0, 131, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_mission_btn.sizePolicy().hasHeightForWidth())
        self.upload_mission_btn.setSizePolicy(sizePolicy)
        self.upload_mission_btn.setObjectName("upload_mission_btn")
        self.waypoint_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        self.waypoint_table.setGeometry(QtCore.QRect(10, 31, 431, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waypoint_table.sizePolicy().hasHeightForWidth())
        self.waypoint_table.setSizePolicy(sizePolicy)
        self.waypoint_table.setObjectName("waypoint_table")
        self.waypoint_table.setColumnCount(3)
        self.waypoint_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.waypoint_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.waypoint_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.waypoint_table.setHorizontalHeaderItem(2, item)
        self.clear_mission_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.clear_mission_btn.setGeometry(QtCore.QRect(190, 0, 113, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_mission_btn.sizePolicy().hasHeightForWidth())
        self.clear_mission_btn.setSizePolicy(sizePolicy)
        self.clear_mission_btn.setObjectName("clear_mission_btn")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.waypoint_table.raise_()
        self.remove_waypoint_btn.raise_()
        self.upload_mission_btn.raise_()
        self.clear_mission_btn.raise_()
        self.label_19.raise_()
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(520, 400, 191, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.commands_drone__actions_deploy_btn = QtWidgets.QPushButton(self.groupBox)
        self.commands_drone__actions_deploy_btn.setGeometry(QtCore.QRect(10, 60, 171, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commands_drone__actions_deploy_btn.sizePolicy().hasHeightForWidth())
        self.commands_drone__actions_deploy_btn.setSizePolicy(sizePolicy)
        self.commands_drone__actions_deploy_btn.setObjectName("commands_drone__actions_deploy_btn")
        self.commands_drone_actions_rth_btn = QtWidgets.QPushButton(self.groupBox)
        self.commands_drone_actions_rth_btn.setGeometry(QtCore.QRect(10, 90, 171, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commands_drone_actions_rth_btn.sizePolicy().hasHeightForWidth())
        self.commands_drone_actions_rth_btn.setSizePolicy(sizePolicy)
        self.commands_drone_actions_rth_btn.setObjectName("commands_drone_actions_rth_btn")
        self.commands_drone_actions_emergency_land_btn = QtWidgets.QPushButton(self.groupBox)
        self.commands_drone_actions_emergency_land_btn.setGeometry(QtCore.QRect(10, 120, 171, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commands_drone_actions_emergency_land_btn.sizePolicy().hasHeightForWidth())
        self.commands_drone_actions_emergency_land_btn.setSizePolicy(sizePolicy)
        self.commands_drone_actions_emergency_land_btn.setObjectName("commands_drone_actions_emergency_land_btn")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(30, 190, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 190, 71, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(190, 40, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(0, 240, 191, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(90, 20, 101, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_8.setGeometry(QtCore.QRect(0, 100, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_8.sizePolicy().hasHeightForWidth())
        self.radioButton_8.setSizePolicy(sizePolicy)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_9.setGeometry(QtCore.QRect(0, 80, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_9.sizePolicy().hasHeightForWidth())
        self.radioButton_9.setSizePolicy(sizePolicy)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_10.setGeometry(QtCore.QRect(0, 60, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_10.sizePolicy().hasHeightForWidth())
        self.radioButton_10.setSizePolicy(sizePolicy)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_11.setGeometry(QtCore.QRect(0, 40, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_11.sizePolicy().hasHeightForWidth())
        self.radioButton_11.setSizePolicy(sizePolicy)
        self.radioButton_11.setObjectName("radioButton_11")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 20, 91, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_14.setGeometry(QtCore.QRect(0, 60, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_14.sizePolicy().hasHeightForWidth())
        self.radioButton_14.setSizePolicy(sizePolicy)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_15.setGeometry(QtCore.QRect(0, 40, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_15.sizePolicy().hasHeightForWidth())
        self.radioButton_15.setSizePolicy(sizePolicy)
        self.radioButton_15.setObjectName("radioButton_15")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(519, 10, 191, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 178))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formLayoutWidget.sizePolicy().hasHeightForWidth())
        self.formLayoutWidget.setSizePolicy(sizePolicy)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dronePositionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dronePositionLabel.sizePolicy().hasHeightForWidth())
        self.dronePositionLabel.setSizePolicy(sizePolicy)
        self.dronePositionLabel.setObjectName("dronePositionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dronePositionLabel)
        self.dronePositionLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dronePositionLineEdit.sizePolicy().hasHeightForWidth())
        self.dronePositionLineEdit.setSizePolicy(sizePolicy)
        self.dronePositionLineEdit.setReadOnly(True)
        self.dronePositionLineEdit.setObjectName("dronePositionLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dronePositionLineEdit)
        self.headingLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headingLabel.sizePolicy().hasHeightForWidth())
        self.headingLabel.setSizePolicy(sizePolicy)
        self.headingLabel.setObjectName("headingLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.headingLabel)
        self.droneHeadingLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.droneHeadingLineEdit.sizePolicy().hasHeightForWidth())
        self.droneHeadingLineEdit.setSizePolicy(sizePolicy)
        self.droneHeadingLineEdit.setReadOnly(True)
        self.droneHeadingLineEdit.setObjectName("droneHeadingLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.droneHeadingLineEdit)
        self.droneSpeedLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.droneSpeedLineEdit.sizePolicy().hasHeightForWidth())
        self.droneSpeedLineEdit.setSizePolicy(sizePolicy)
        self.droneSpeedLineEdit.setReadOnly(True)
        self.droneSpeedLineEdit.setObjectName("droneSpeedLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.droneSpeedLineEdit)
        self.altitudeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altitudeLabel.sizePolicy().hasHeightForWidth())
        self.altitudeLabel.setSizePolicy(sizePolicy)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.altitudeLabel)
        self.droneAltitudeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.droneAltitudeLineEdit.sizePolicy().hasHeightForWidth())
        self.droneAltitudeLineEdit.setSizePolicy(sizePolicy)
        self.droneAltitudeLineEdit.setReadOnly(True)
        self.droneAltitudeLineEdit.setObjectName("droneAltitudeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.droneAltitudeLineEdit)
        self.speedLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedLabel.sizePolicy().hasHeightForWidth())
        self.speedLabel.setSizePolicy(sizePolicy)
        self.speedLabel.setObjectName("speedLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.speedLabel)
        self.batteryLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryLabel.sizePolicy().hasHeightForWidth())
        self.batteryLabel.setSizePolicy(sizePolicy)
        self.batteryLabel.setObjectName("batteryLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.batteryLabel)
        self.statusLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.statusLabel)
        self.droneStatusLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.droneStatusLineEdit.sizePolicy().hasHeightForWidth())
        self.droneStatusLineEdit.setSizePolicy(sizePolicy)
        self.droneStatusLineEdit.setReadOnly(True)
        self.droneStatusLineEdit.setObjectName("droneStatusLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.droneStatusLineEdit)
        self.droneBatteryLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.droneBatteryLineEdit.sizePolicy().hasHeightForWidth())
        self.droneBatteryLineEdit.setSizePolicy(sizePolicy)
        self.droneBatteryLineEdit.setReadOnly(True)
        self.droneBatteryLineEdit.setObjectName("droneBatteryLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.droneBatteryLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 171, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.formLayoutWidget_2.setSizePolicy(sizePolicy)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dronePositionLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dronePositionLabel_2.sizePolicy().hasHeightForWidth())
        self.dronePositionLabel_2.setSizePolicy(sizePolicy)
        self.dronePositionLabel_2.setObjectName("dronePositionLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dronePositionLabel_2)
        self.dronePositionLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dronePositionLineEdit_2.sizePolicy().hasHeightForWidth())
        self.dronePositionLineEdit_2.setSizePolicy(sizePolicy)
        self.dronePositionLineEdit_2.setReadOnly(True)
        self.dronePositionLineEdit_2.setObjectName("dronePositionLineEdit_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dronePositionLineEdit_2)
        self.velocityLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_3.sizePolicy().hasHeightForWidth())
        self.velocityLabel_3.setSizePolicy(sizePolicy)
        self.velocityLabel_3.setObjectName("velocityLabel_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.velocityLabel_3)
        self.velocityLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLineEdit_2.sizePolicy().hasHeightForWidth())
        self.velocityLineEdit_2.setSizePolicy(sizePolicy)
        self.velocityLineEdit_2.setReadOnly(True)
        self.velocityLineEdit_2.setObjectName("velocityLineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.velocityLineEdit_2)
        self.velocityLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_4.sizePolicy().hasHeightForWidth())
        self.velocityLabel_4.setSizePolicy(sizePolicy)
        self.velocityLabel_4.setObjectName("velocityLabel_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.velocityLabel_4)
        self.headingLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headingLineEdit_2.sizePolicy().hasHeightForWidth())
        self.headingLineEdit_2.setSizePolicy(sizePolicy)
        self.headingLineEdit_2.setReadOnly(True)
        self.headingLineEdit_2.setObjectName("headingLineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.headingLineEdit_2)
        self.statusLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel_3.sizePolicy().hasHeightForWidth())
        self.statusLabel_3.setSizePolicy(sizePolicy)
        self.statusLabel_3.setObjectName("statusLabel_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.statusLabel_3)
        self.statusLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLineEdit_3.sizePolicy().hasHeightForWidth())
        self.statusLineEdit_3.setSizePolicy(sizePolicy)
        self.statusLineEdit_3.setReadOnly(True)
        self.statusLineEdit_3.setObjectName("statusLineEdit_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.statusLineEdit_3)
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(1750, 19, 161, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formLayoutWidget_9.sizePolicy().hasHeightForWidth())
        self.formLayoutWidget_9.setSizePolicy(sizePolicy)
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.latLabel = QtWidgets.QLabel(self.formLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latLabel.sizePolicy().hasHeightForWidth())
        self.latLabel.setSizePolicy(sizePolicy)
        self.latLabel.setObjectName("latLabel")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.latLabel)
        self.mission_plan_map_mouse_over_lat_LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mission_plan_map_mouse_over_lat_LineEdit.sizePolicy().hasHeightForWidth())
        self.mission_plan_map_mouse_over_lat_LineEdit.setSizePolicy(sizePolicy)
        self.mission_plan_map_mouse_over_lat_LineEdit.setObjectName("mission_plan_map_mouse_over_lat_LineEdit")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mission_plan_map_mouse_over_lat_LineEdit)
        self.long_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_label.sizePolicy().hasHeightForWidth())
        self.long_label.setSizePolicy(sizePolicy)
        self.long_label.setObjectName("long_label")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.long_label)
        self.mission_plan_map_mouse_over_long_LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mission_plan_map_mouse_over_long_LineEdit.sizePolicy().hasHeightForWidth())
        self.mission_plan_map_mouse_over_long_LineEdit.setSizePolicy(sizePolicy)
        self.mission_plan_map_mouse_over_long_LineEdit.setObjectName("mission_plan_map_mouse_over_long_LineEdit")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mission_plan_map_mouse_over_long_LineEdit)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(870, 60, 1011, 901))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 1161, 821))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mission_planner_map_image = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mission_planner_map_image.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mission_planner_map_image.setContentsMargins(0, 0, 0, 0)
        self.mission_planner_map_image.setObjectName("mission_planner_map_image")
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_7)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 20, 1361, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.launchpad_monitoring_videofeed_1 = QVideoWidget(self.tab_3)
        self.launchpad_monitoring_videofeed_1.setGeometry(QtCore.QRect(20, 20, 921, 491))
        self.launchpad_monitoring_videofeed_1.setObjectName("launchpad_monitoring_videofeed_1")
        self.launchpad_monitoring_videofeed_2 = QVideoWidget(self.tab_3)
        self.launchpad_monitoring_videofeed_2.setGeometry(QtCore.QRect(970, 20, 921, 491))
        self.launchpad_monitoring_videofeed_2.setObjectName("launchpad_monitoring_videofeed_2")
        self.launchpad_monitoring_videofeed_3 = QVideoWidget(self.tab_3)
        self.launchpad_monitoring_videofeed_3.setGeometry(QtCore.QRect(20, 520, 921, 491))
        self.launchpad_monitoring_videofeed_3.setObjectName("launchpad_monitoring_videofeed_3")
        self.launchpad_monitoring_videofeed_4 = QVideoWidget(self.tab_3)
        self.launchpad_monitoring_videofeed_4.setGeometry(QtCore.QRect(970, 520, 921, 491))
        self.launchpad_monitoring_videofeed_4.setObjectName("launchpad_monitoring_videofeed_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 10, 871, 381))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(30, 30, 231, 341))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.activeFlightsLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.activeFlightsLabel.setObjectName("activeFlightsLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.activeFlightsLabel)
        self.activeFlightsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.activeFlightsLineEdit.setObjectName("activeFlightsLineEdit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activeFlightsLineEdit)
        self.totalAirTimeLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.totalAirTimeLabel.setObjectName("totalAirTimeLabel")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.totalAirTimeLabel)
        self.totalAirTimeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.totalAirTimeLineEdit.setObjectName("totalAirTimeLineEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalAirTimeLineEdit)
        self.totalLogTimeLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.totalLogTimeLabel.setObjectName("totalLogTimeLabel")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.totalLogTimeLabel)
        self.totalLogTimeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.totalLogTimeLineEdit.setObjectName("totalLogTimeLineEdit")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.totalLogTimeLineEdit)
        self.totalPhotosLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.totalPhotosLabel.setObjectName("totalPhotosLabel")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.totalPhotosLabel)
        self.totalPhotosLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.totalPhotosLineEdit.setObjectName("totalPhotosLineEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.totalPhotosLineEdit)
        self.totalVideosLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.totalVideosLabel.setObjectName("totalVideosLabel")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.totalVideosLabel)
        self.totalVideosLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.totalVideosLineEdit.setObjectName("totalVideosLineEdit")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.totalVideosLineEdit)
        self.totalDistanceTraveledLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.totalDistanceTraveledLabel.setObjectName("totalDistanceTraveledLabel")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.totalDistanceTraveledLabel)
        self.totalDistanceTraveledLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.totalDistanceTraveledLineEdit.setObjectName("totalDistanceTraveledLineEdit")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.totalDistanceTraveledLineEdit)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_5.setGeometry(QtCore.QRect(320, 30, 231, 341))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_5)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 90, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_5)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(40, 190, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(0, 170, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(0, 260, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.frame_5)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(40, 280, 160, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame_5)
        self.lcdNumber_2.setGeometry(QtCore.QRect(60, 130, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.frame_5)
        self.lcdNumber_4.setGeometry(QtCore.QRect(60, 30, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.frame_5)
        self.lcdNumber_5.setGeometry(QtCore.QRect(60, 230, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_6.setGeometry(QtCore.QRect(600, 30, 231, 341))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_4.setEnabled(True)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(40, 70, 160, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(40, 160, 160, 22))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(0, 40, 231, 20)) 
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(0, 130, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(0, 230, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(40, 260, 160, 22))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 400, 431, 601))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget.setGeometry(QtCore.QRect(15, 30, 401, 561))
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(470, 400, 431, 601))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(1010, 10, 431, 981))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(1450, 10, 431, 981))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 301, 991))
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_8)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 281, 951))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.camera1IPAddressLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.camera1IPAddressLabel_4.setObjectName("camera1IPAddressLabel_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera1IPAddressLabel_4)
        self.camera1IPAddressLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.camera1IPAddressLineEdit_4.setObjectName("camera1IPAddressLineEdit_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera1IPAddressLineEdit_4)
        self.uASIPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.uASIPAddressLabel.setObjectName("uASIPAddressLabel")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.uASIPAddressLabel)
        self.uASIPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.uASIPAddressLineEdit.setObjectName("uASIPAddressLineEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uASIPAddressLineEdit)
        self.camera2IPAddressLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.camera2IPAddressLabel_4.setObjectName("camera2IPAddressLabel_4")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.camera2IPAddressLabel_4)
        self.camera2IPAddressLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.camera2IPAddressLineEdit_4.setObjectName("camera2IPAddressLineEdit_4")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera2IPAddressLineEdit_4)
        self.config_uas_update_btn = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.config_uas_update_btn.setObjectName("config_uas_update_btn")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.config_uas_update_btn)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(320, 10, 301, 991))
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_9)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 281, 951))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.camera1IPAddressLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.camera1IPAddressLabel_3.setObjectName("camera1IPAddressLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera1IPAddressLabel_3)
        self.camera1IPAddressLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.camera1IPAddressLineEdit_3.setObjectName("camera1IPAddressLineEdit_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera1IPAddressLineEdit_3)
        self.controllerIPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.controllerIPAddressLabel.setObjectName("controllerIPAddressLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.controllerIPAddressLabel)
        self.controllerIPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.controllerIPAddressLineEdit.setObjectName("controllerIPAddressLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.controllerIPAddressLineEdit)
        self.camera2IPAddressLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.camera2IPAddressLabel_3.setObjectName("camera2IPAddressLabel_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.camera2IPAddressLabel_3)
        self.camera2IPAddressLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.camera2IPAddressLineEdit_3.setObjectName("camera2IPAddressLineEdit_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera2IPAddressLineEdit_3)
        self.config_launchpad_update_btn = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.config_launchpad_update_btn.setObjectName("config_launchpad_update_btn")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.config_launchpad_update_btn)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(630, 10, 301, 991))
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_10)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 281, 951))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.camera1IPAddressLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.camera1IPAddressLabel_2.setObjectName("camera1IPAddressLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera1IPAddressLabel_2)
        self.mapImageLocationLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.mapImageLocationLineEdit.setReadOnly(True)
        self.mapImageLocationLineEdit.setObjectName("mapImageLocationLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mapImageLocationLineEdit)
        self.map_select_file_btn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.map_select_file_btn.setObjectName("map_select_file_btn")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.map_select_file_btn)
        self.corner_1_lat_AddressLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.corner_1_lat_AddressLabel.setObjectName("corner_1_lat_AddressLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.corner_1_lat_AddressLabel)
        self.map_corner_1_lat = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.map_corner_1_lat.setObjectName("map_corner_1_lat")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.map_corner_1_lat)
        self.corner_1_long_AddressLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.corner_1_long_AddressLabel.setObjectName("corner_1_long_AddressLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.corner_1_long_AddressLabel)
        self.map_corner_1_long = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.map_corner_1_long.setObjectName("map_corner_1_long")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.map_corner_1_long)
        self.corner_4_lat_AddressLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.corner_4_lat_AddressLabel.setObjectName("corner_4_lat_AddressLabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.corner_4_lat_AddressLabel)
        self.map_corner_4_lat = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.map_corner_4_lat.setObjectName("map_corner_4_lat")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.map_corner_4_lat)
        self.corner_4_long_AddressLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.corner_4_long_AddressLabel.setObjectName("corner_4_long_AddressLabel")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.corner_4_long_AddressLabel)
        self.map_corner_4_long = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.map_corner_4_long.setObjectName("map_corner_4_long")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.map_corner_4_long)
        self.config_map_update_btn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.config_map_update_btn.setObjectName("config_map_update_btn")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.config_map_update_btn)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(940, 10, 301, 991))
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_11)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 29, 281, 951))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.camera1IPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.camera1IPAddressLabel.setObjectName("camera1IPAddressLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera1IPAddressLabel)
        self.camera1IPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.camera1IPAddressLineEdit.setObjectName("camera1IPAddressLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera1IPAddressLineEdit)
        self.camera2IPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.camera2IPAddressLabel.setObjectName("camera2IPAddressLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.camera2IPAddressLabel)
        self.camera2IPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.camera2IPAddressLineEdit.setObjectName("camera2IPAddressLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera2IPAddressLineEdit)
        self.camera3IPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.camera3IPAddressLabel.setObjectName("camera3IPAddressLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.camera3IPAddressLabel)
        self.camera3IPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.camera3IPAddressLineEdit.setObjectName("camera3IPAddressLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera3IPAddressLineEdit)
        self.camera4IPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.camera4IPAddressLabel.setObjectName("camera4IPAddressLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.camera4IPAddressLabel)
        self.camera4IPAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.camera4IPAddressLineEdit.setObjectName("camera4IPAddressLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.camera4IPAddressLineEdit)
        self.config_camera_update_btn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.config_camera_update_btn.setObjectName("config_camera_update_btn")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.config_camera_update_btn)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(1250, 10, 301, 991))
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_12)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 281, 951))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.camera1IPAddressLabel_5 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.camera1IPAddressLabel_5.setObjectName("camera1IPAddressLabel_5")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera1IPAddressLabel_5)
        self.camera1IPAddressLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.camera1IPAddressLineEdit_2.setObjectName("camera1IPAddressLineEdit_2")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera1IPAddressLineEdit_2)
        self.camera2IPAddressLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.camera2IPAddressLabel_2.setObjectName("camera2IPAddressLabel_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.camera2IPAddressLabel_2)
        self.camera2IPAddressLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.camera2IPAddressLineEdit_2.setObjectName("camera2IPAddressLineEdit_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera2IPAddressLineEdit_2)
        self.config_camera_update_btn_2 = QtWidgets.QPushButton(self.formLayoutWidget_8)
        self.config_camera_update_btn_2.setObjectName("config_camera_update_btn_2")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.config_camera_update_btn_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        self.menuHEROTECh8 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menuHEROTECh8.setFont(font)
        self.menuHEROTECh8.setObjectName("menuHEROTECh8")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.menuHEROTECh8.addAction(self.actionConnect)
        self.menubar.addAction(self.menuHEROTECh8.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MISSION PLANNER"))
        self.label_2.setText(_translate("MainWindow", "MISSION PROGRESS"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Trajectory"))
        self.remove_waypoint_btn.setText(_translate("MainWindow", "(-)"))
        self.upload_mission_btn.setText(_translate("MainWindow", "Upload Mission"))
        item = self.waypoint_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Latitude"))
        item = self.waypoint_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Longitude"))
        item = self.waypoint_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Altitude"))
        self.clear_mission_btn.setText(_translate("MainWindow", "Clear Mission"))
        self.label_19.setText(_translate("MainWindow", "Waypoint List"))
        self.groupBox.setTitle(_translate("MainWindow", "COMMANDS"))
        self.commands_drone__actions_deploy_btn.setText(_translate("MainWindow", "Deploy"))
        self.commands_drone_actions_rth_btn.setText(_translate("MainWindow", "Return to Home"))
        self.commands_drone_actions_emergency_land_btn.setText(_translate("MainWindow", "Emergency Land"))
        self.radioButton.setText(_translate("MainWindow", "Auto"))
        self.radioButton_2.setText(_translate("MainWindow", "Manual"))
        self.label_3.setText(_translate("MainWindow", "CONTROL MODE"))
        self.label_4.setText(_translate("MainWindow", "ACTIONS"))
        self.label_5.setText(_translate("MainWindow", "DRONE"))
        self.label_6.setText(_translate("MainWindow", "DRONE"))
        self.label_7.setText(_translate("MainWindow", "CAMERA"))
        self.radioButton_8.setText(_translate("MainWindow", "90 degrees"))
        self.radioButton_9.setText(_translate("MainWindow", "60 degrees"))
        self.radioButton_10.setText(_translate("MainWindow", "30 degrees"))
        self.radioButton_11.setText(_translate("MainWindow", "0 degrees"))
        self.label_13.setText(_translate("MainWindow", "ANGLE"))
        self.radioButton_14.setText(_translate("MainWindow", "Thermal"))
        self.radioButton_15.setText(_translate("MainWindow", "Visual"))
        self.label_14.setText(_translate("MainWindow", "MODE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FLIGHT DATA"))
        self.label_8.setText(_translate("MainWindow", "DRONE"))
        self.label_9.setText(_translate("MainWindow", "LAUNCHPAD"))
        self.dronePositionLabel.setText(_translate("MainWindow", "Position"))
        self.headingLabel.setText(_translate("MainWindow", "Heading"))
        self.altitudeLabel.setText(_translate("MainWindow", "Altitude"))
        self.speedLabel.setText(_translate("MainWindow", "Speed"))
        self.batteryLabel.setText(_translate("MainWindow", "Battery"))
        self.statusLabel.setText(_translate("MainWindow", "Status"))
        self.dronePositionLabel_2.setText(_translate("MainWindow", "Location"))
        self.velocityLabel_3.setText(_translate("MainWindow", "Status"))
        self.velocityLabel_4.setText(_translate("MainWindow", "Velocity"))
        self.statusLabel_3.setText(_translate("MainWindow", "Status"))
        self.latLabel.setText(_translate("MainWindow", "Lat: "))
        self.long_label.setText(_translate("MainWindow", "Long:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "MISSION PLANNING"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "LAUNCHPAD MONITORING"))
        self.groupBox_3.setTitle(_translate("MainWindow", "FLIGHT DASHBOARD"))
        self.activeFlightsLabel.setText(_translate("MainWindow", "Active Flights"))
        self.totalAirTimeLabel.setText(_translate("MainWindow", "Total Air Time"))
        self.totalLogTimeLabel.setText(_translate("MainWindow", "Total Log Time"))
        self.totalPhotosLabel.setText(_translate("MainWindow", "Total Photos"))
        self.totalVideosLabel.setText(_translate("MainWindow", "Total Videos"))
        self.totalDistanceTraveledLabel.setText(_translate("MainWindow", "Distance Traveled "))
        self.label_11.setText(_translate("MainWindow", "Longest Flight Time"))
        self.label_12.setText(_translate("MainWindow", "Longest Kilometrage"))
        self.label_15.setText(_translate("MainWindow", "Longest Kilometrage"))
        self.label_16.setText(_translate("MainWindow", "Hottest Battery Temperature"))
        self.label_17.setText(_translate("MainWindow", "Highest Altitude"))
        self.label_18.setText(_translate("MainWindow", "Fastest Speed"))
        self.groupBox_4.setTitle(_translate("MainWindow", "FLIGHT LOGGING"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Test 1 "))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Test 2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("MainWindow", "BATTERY MONITORING"))
        self.groupBox_6.setTitle(_translate("MainWindow", "MOTOR AND PROPELLER"))
        self.groupBox_7.setTitle(_translate("MainWindow", "ENVIRONMENTAL EFFECTS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "MAINTENANCE REPORTING"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "CONTACT"))
        self.groupBox_8.setTitle(_translate("MainWindow", "UAS Parameters"))
        self.camera1IPAddressLabel_4.setText(_translate("MainWindow", "UAS ID"))
        self.uASIPAddressLabel.setText(_translate("MainWindow", "UAS IP Address"))
        self.camera2IPAddressLabel_4.setText(_translate("MainWindow", "UAS Icon"))
        self.config_uas_update_btn.setText(_translate("MainWindow", "Update"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Launchpad Parameters"))
        self.camera1IPAddressLabel_3.setText(_translate("MainWindow", "Launchpad ID"))
        self.controllerIPAddressLabel.setText(_translate("MainWindow", "Controller IP Address"))
        self.camera2IPAddressLabel_3.setText(_translate("MainWindow", "Launchpad Icon"))
        self.config_launchpad_update_btn.setText(_translate("MainWindow", "Update"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Map Parameters"))
        self.camera1IPAddressLabel_2.setText(_translate("MainWindow", "Map Image Location"))
        self.map_select_file_btn.setText(_translate("MainWindow", "Select File"))
        self.corner_1_lat_AddressLabel.setText(_translate("MainWindow", "Top Left Latitude"))
        self.corner_1_long_AddressLabel.setText(_translate("MainWindow", "Top Right Longitude"))
        self.corner_4_lat_AddressLabel.setText(_translate("MainWindow", "Bottom Right Latitude"))
        self.corner_4_long_AddressLabel.setText(_translate("MainWindow", "Bottom Right Longitude"))
        self.config_map_update_btn.setText(_translate("MainWindow", "Update"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Camera Parameters"))
        self.camera1IPAddressLabel.setText(_translate("MainWindow", "Camera 1 IP Address"))
        self.camera2IPAddressLabel.setText(_translate("MainWindow", "Camera 2 IP Address"))
        self.camera3IPAddressLabel.setText(_translate("MainWindow", "Camera 3 IP Address"))
        self.camera4IPAddressLabel.setText(_translate("MainWindow", "Camera 4 IP Address"))
        self.config_camera_update_btn.setText(_translate("MainWindow", "Update"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Maintenance Monitoring Parameters"))
        self.camera1IPAddressLabel_5.setText(_translate("MainWindow", "AirData Signin"))
        self.camera2IPAddressLabel_2.setText(_translate("MainWindow", "Password"))
        self.config_camera_update_btn_2.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "CONFIGURATION"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "DEVELOPER"))
        self.menuHEROTECh8.setTitle(_translate("MainWindow", "HEROTECH8"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
